### PR TITLE
Add config options documentation for Java VM and Cromwell

### PR DESCRIPTION
**Pull request by wshands**

### CODE REVIEW

**Comment by denis-yuen** [comment]
Looks like circle-ci build needs investigation

**Comment by wshands** [comment]
Not sure what to do about the Seven Bridges link; it says:
_We apologise if you've found a broken link. We're having some issues with our software and are working with our documentation hosting service to repair the broken links..

Please try using the search box above to find what you're looking for. Alternatively, if you've tried to access docs.sevenbridges.com/<your-page> please instead try accessing docs.sevenbridges.com/docs/<your-page> (i.e. insert '/docs' after the '.com'.

In the meantime, we're working to repair any dead links in the documentation.

All the best,
Seven Bridges docs team_

**Comment by denis-yuen** [comment]
It has been moved to https://docs.cancergenomicscloud.org/docs/run-dockstore-apps-on-the-cgc

**Comment by wshands** [comment]
Fixed SB link error

**Pull request merged**
