### PR TITLE
Add default latest version tag info

### PR DESCRIPTION
**Pull request by david4096**
Adds a note about the new .dockstore.yml tag

### CODE REVIEW

**Review by garyluu — APPROVED** [review]

**Comment by denis-yuen** [comment]
Should this be develop? @garyluu

**Comment by garyluu** [comment]
> Should this be develop? @garyluu

ah right, probably not

**Review by coverbeck — APPROVED** [review]
Pending re-targetting branch.

**Review by NatalieEO — APPROVED** [review]

**Review by denis-yuen — CHANGES_REQUESTED** [review]
merge with release branch to make it into stable

**Comment by david4096** [comment]
@denis-yuen I changed the target to the 1.11 release branch.

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
