### PR TITLE
shorten title, fix formatting, typos

### PR DESCRIPTION
**Pull request by bethsheets**

### CODE REVIEW

**Comment by denis-yuen** [comment]
This is rendering at https://docs.dockstore.org/en/bestpractices/advanced-topics/best-practices/best-practices-secure-fair-workflows.html

Comparing, I think there's some extra bolding in the first section that was unintentional. 
`<docs/getting-started/github-apps/github-apps-landing-page> ` is a broken link

There are more broken links in the FAIR section

**Review by bethsheets — COMMENTED** [review]
thanks for reviewing the paths!  LGTM

**Comment by denis-yuen** [comment]
Hmmm, its not still rendering properly for me ... weird ...

**Comment by coverbeck** [comment]
> Hmmm, its not still rendering properly for me ... weird ...

Yeah, seeing the same, it's odd. Even the the title is the old one. I'm going to push a trivial change to see if a new build works.

**Comment by coverbeck** [comment]
I think I see, @bethsheets created a new branch, bethsheets-bestpractices-review, but we're rendering bestpractices. I'm going to merge this PR to bestpractices and close this PR, then create a new PR for bestpractices -> develop. If there are still issues, Beth, just modify the bestpractices branch directly.

**Pull request merged**
