### PR TITLE
Possibly final updates for 1.7.0

### PR DESCRIPTION
**Pull request by denis-yuen**
Noticed while reviewing https://github.com/dockstore/dockstore/issues/2826
Also https://github.com/dockstore/dockstore/issues/2823#issuecomment-536725500

Also dockstore/dockstore#2925

### CODE REVIEW

**Comment by denis-yuen** [comment]
FYI three links remaining as warnings 
```

/root/project/docs/news/2018-04-05-Dockstore-1.4.0.rst:35: WARNING: unknown document: /advanced-topics/advanced-features.html#alternative-cwl-launchers
/root/project/docs/news/2018-04-05-Dockstore-1.4.0.rst:40: WARNING: unknown document: /advanced-topics/advanced-features.html#notifications
/root/project/docs/news/2018-09-12-Dockstore-1.5.0.rst:54: WARNING: unknown document: /faq.html#what-is-a-verified-tool-or-workflow
/root/project/docs/news/2019-04-08-Dockstore-1.6.0.rst:16: WARNING: unknown document: /faq.html#what-is-a-verified-tool-or-workflow
```

**Comment by coverbeck** [comment]
Does this also fix dockstore/dockstore#2925? I haven't looked yet, but if so, should mention in commit message

**Comment by denis-yuen** [comment]
> Does this also fix [dockstore/dockstore#2925](https://github.com/dockstore/dockstore/issues/2925)? I haven't looked yet, but if so, should mention in commit message

No, I don't believe so. 

Thinking that link checker is overlooking those but checking these links for the changelogs in one of two situations 

1) Before this PR, the links looked like `https://docs.dockstore.org/docs/publisher-tutorials/guid-alias/` which would break because they were just external links that broke when we moved `docs.dockstore.org` to point at readthedocs
2) After this PR , it looks like link checker is checking links that look like 
```
:doc:`verified <faq.html#what-is-a-verified-tool-or-workflow>`
```

The "See Also" links look like 
```
`AWS Batch </advanced-topics/aws-batch/>`__
```
which doesn't match either format (and don't seem to work)

**Comment by denis-yuen** [comment]
On the other hand it looks like links like 
```
:doc:`verified <faq.html#what-is-a-verified-tool-or-workflow>`
``` 
foul up bulleted lists. 

Ironically, have to work with links that look like 

```
`AWS Batch <../advanced-topics/aws-batch/>`__
```

(Note the relative directory changes)

**Pull request merged**
