### PR TITLE
Merge 1.11 documentation

### PR DESCRIPTION
**Pull request by GFJHogue**
Pretending this is hubflow and that develop is master

### CODE REVIEW

**Comment by garyluu** [comment]
release/1.10 was already merged to master. so master is the "stable" version and should be hubflow model already

**Comment by GFJHogue** [comment]
> release/1.10 was already merged to master. so master is the "stable" version and should be hubflow model already. not sure why there's so many conflicts though.

I see, so I assume the front-facing docs will show the 1.11 changes in master eventually?

**Comment by garyluu** [comment]
> > release/1.10 was already merged to master. so master is the "stable" version and should be hubflow model already. not sure why there's so many conflicts though.
> 
> I see, so I assume the front-facing docs will show the 1.11 changes in master eventually? https://docs.dockstore.org/ still seems to defualt to develop.

Next deploy is supposed to change to "stable" (with 1.11 merged to master, and then master merged back to develop)

**Comment by denis-yuen** [comment]
> Pretending this is hubflow and that develop is master

To clarify, this PR is to help us review documentation changes for 1.11 as a whole including the publish changes and the plan is to merge this after we release 1.11?

**Comment by GFJHogue** [comment]
> > > release/1.10 was already merged to master. so master is the "stable" version and should be hubflow model already. not sure why there's so many conflicts though.
> > 
> > 
> > I see, so I assume the front-facing docs will show the 1.11 changes in master eventually? https://docs.dockstore.org/ still seems to defualt to develop.
> 
> Next deploy is supposed to change to "stable" (with 1.11 merged to master, and then master merged back to develop)

Makes sense, in that case I'll close this

**Pull request closed without merging**
