### PR TITLE
change version to empty

### PR DESCRIPTION
**Pull request by agduncan94**
Update release version
https://github.com/dockstore/dockstore/issues/3128

Version is being included in the docs title. Set to null so that docs are not versioned.

### CODE REVIEW

**Comment by denis-yuen** [comment]
Actually, I didn't carefully read the ticket. Is the title really the only place this shows up?
If so, maybe we just shouldn't have it and just mark features with what release they are available in. That way, it is harder for docs to be out-of-date or ahead of themselves

**Comment by agduncan94** [comment]
Since we don't do releases for the docs, there is actually nowhere visible to the user where we say 1.8.0 for example. It is only in the page source.

**Comment by garyluu** [comment]
> Ok, then I'd recommend experimenting with just taking it out and seeing if it affects anything other than
> Screenshot from 2020-01-13 10-35-51

Ah, I can't even see that in Chrome.  The title gets truncated.

**Comment by agduncan94** [comment]
@garyluu that is because you have hundreds of windows open :laughing:

**Comment by coverbeck** [comment]
It also shows up if you link to the docs from a Google Doc.

**Comment by agduncan94** [comment]
@denis-yuen It looks like setting the version and release to blank the title looks like 'Welcome to Dockstore Documentation - Dockstore Documentation'. Is this better?

**Pull request merged**
