### PR TITLE
Turn warnings into errors during make

### PR DESCRIPTION
**Pull request by aofarrel**
***If this is merged before docker_instructions.md is turned into a format compatible with rst, it will break develop.***

`-W` turns warnings into errors
`--keep-going` will continue building even after the first error/warning

This affects `make html` both locally and [on CircleCI](https://app.circleci.com/pipelines/github/dockstore/dockstore-documentation/745/workflows/436a7d17-6948-4cd4-83a2-14900e1da4e1/jobs/761).

#154 fixes docker_instructions.md and should be merged before this.

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]
> -W turns warnings into errors
--keep-going will continue building even after the first error/warning

Just to make sure, even if it keeps going, the end result will still be an error, right?

Background for other reviewers: there are warnings in the build that all look worth fixing -- text gets not displayed, etc., so after discussing with Ash, he volunteered to fix.

**Review by NatalieEO — APPROVED** [review]

**Review by garyluu — COMMENTED** [review]
i was here, waiting for tests to pass

**Comment by aofarrel** [comment]
> > -W turns warnings into errors
> > --keep-going will continue building even after the first error/warning
> 
> Just to make sure, even if it keeps going, the end result will still be an error, right?

Yes. --keep-going will continue after the first warning so you can catch more than one at a time, but the end result will be a failure both locally [and on CircleCI](https://app.circleci.com/pipelines/github/dockstore/dockstore-documentation/745/workflows/436a7d17-6948-4cd4-83a2-14900e1da4e1/jobs/761).

**Comment by aofarrel** [comment]
Rebase complete, tests are now passing. Huzzah!

**Review by garyluu — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]
Thanks for cleaning this up! No errors/warnings in the build any more.

**Comment by aofarrel** [comment]
Side note: https://github.com/sphinx-doc/sphinx/issues/9979#issuecomment-997324673

**Pull request merged**
